version: "1"
rules:
  - base: master
    upstream: NexusForever:master
  - base: develop
    upstream: NexusForever:develop
    mergeMethod: hardreset
    mergeUnstable: false 
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
