version: "3"

services:
  auth:
    image: nexusforever-auth
    networks:
      - default
      - nexusforever
    ports:
      - "23115:23115/tcp"
    volumes:
      - type: bind
        source: ./devconfig/AuthServer.json
        target: /app/AuthServer.json     
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  sts:
    image: nexusforever-sts
    networks:
      - default
      - nexusforever
    ports:
      - "6600:6600/tcp"
    volumes:
      - type: bind
        source: ./devconfig/StsServer.json
        target: /app/StsServer.json   
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  world:
    image: nexusforever-world
    networks:
      - default
      - nexusforever
    ports:
      - "24000:24000/tcp"
    volumes:
      - type: bind
        source: ./devconfig/WorldServer.json
        target: /app/WorldServer.json   
      - nexusforever-tables:/app/tlb
      - nexusforever-maps:/app/map
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  default:
  nexusforever:

volumes:
  nexusforever-config:
    driver: local
  nexusforever-tables:
    driver: local
  nexusforever-maps:
    driver: local