name: Build Docker containers
on:
  push:

jobs:
  #
  tests:
    name: Perform Solution Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
       
  #
  publish-server:
    name: Build/Publish ${{ matrix.serverName }} Server
    runs-on: ubuntu-latest
    needs: tests
    strategy:
      fail-fast: false
      matrix:
        serverName:
          - World
          - Sts
          - Auth
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - 
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ matrix.serverName }}
      -
        name: Build/Publish
        run: |
          docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/nexusforever-${{ steps.string.outputs.lowercase }}:latest --build-arg ServerExecutable=${{ matrix.serverName }}Server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nexusforever-${{ steps.string.outputs.lowercase }}:latest