name: Build Docker containers
on:
  push:

jobs:
  tests:
    name: Perform Solution Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - 
        name: Install dependencies
        working-directory: ./Source
        run: dotnet restore NexusForever.sln
      - 
        name: Build
        working-directory: ./Source
        run: dotnet build --configuration Release --no-restore NexusForever.sln

  publish-server:
    name: Build/Publish ${{ matrix.serverName }} Server
    runs-on: ubuntu-latest
    needs: tests
    strategy:
      fail-fast: false
      matrix:
        serverName:
          - World
          - Sts
          - Auth
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - 
        name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"
      - 
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ matrix.serverName }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nexusforever-${{ steps.string.outputs.lowercase }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nexusforever-${{ steps.string.outputs.lowercase }}:${{ steps.sha_tag.outputs.tag }}
          build-args: |
            ServerExecutable=${{ matrix.serverName }}Server