name: Build Docker containers
on:
  push:

jobs:
  tests:
    name: Perform Solution Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - 
        name: Install dependencies
        working-directory: ./Source
        run: dotnet restore NexusForever.sln
      - 
        name: Build
        working-directory: ./Source
        run: dotnet build --configuration Release --no-restore NexusForever.sln

  publish-server:
    name: Build/Publish ${{ matrix.serverName }} Server
    runs-on: ubuntu-latest
    needs: tests
    strategy:
      fail-fast: false
      matrix:
        serverName:
          - World
          - Sts
          - Auth
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - 
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ matrix.serverName }}
      -
        name: Build/Publish
        run: |
          docker build . --tag nexusforever-${{ steps.string.outputs.lowercase }}:latest --build-arg ServerExecutable=${{ matrix.serverName }}Server
          docker push nexusforever-${{ steps.string.outputs.lowercase }}:latest